apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: shared-workflows
  annotations:
    backstage.io/kubernetes-id: shared-workflows
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Zaperex-Test-Org/shared-workflows
spec:
  type: service
  lifecycle: production
  owner: user:default/zaperex
