name: Issue Management

on:
  workflow_call:
    inputs:
      project_id:
        type: number
        required: true

jobs:
  add-issue-to-project:
    name: Manage incoming issues
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v1.2.1
        with:
          app_id: ${{ vars.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Add issue to project
        run: gh project item-add ${{ inputs.project_id }} --owner ${{ github.event.organization.login }} --url ${{ github.event.issue.html_url }}
        env:
          # token needs to have read/write permissions for projects on org level
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
